import { Pet } from '@/types/pet';

export const mockPets: Pet[] = [
  // Dogs
  {
    id: "1",
    name: "Buddy",
    type: "dog",
    breed: "Golden Retriever",
    age: "3 years",
    gender: "male",
    size: "large",
    description: "Buddy is a friendly, energetic Golden Retriever who loves to play fetch and go for long walks. He's great with kids and other dogs.",
    imageUrl: "https://images.pexels.com/photos/2253275/pexels-photo-2253275.jpeg",
    location: "New York, NY",
    status: "available",
  },
  {
    id: "2",
    name: "Luna",
    type: "dog",
    breed: "German Shepherd",
    age: "2 years",
    gender: "female",
    size: "large",
    description: "Luna is an intelligent and loyal German Shepherd. She's well-trained and makes an excellent guard dog.",
    imageUrl: "https://images.pexels.com/photos/333083/pexels-photo-333083.jpeg",
    location: "Los Angeles, CA",
    status: "available",
  },
  {
    id: "3",
    name: "Max",
    type: "dog",
    breed: "Beagle",
    age: "1 year",
    gender: "male",
    size: "medium",
    description: "Max is a playful Beagle puppy with boundless energy. He's still learning basic commands but is very food-motivated and eager to please.",
    imageUrl: "https://images.pexels.com/photos/733416/pexels-photo-733416.jpeg",
    location: "Chicago, IL",
    status: "available",
  },
  {
    id: "4",
    name: "Bella",
    type: "cat",
    breed: "Maine Coon",
    age: "4 years",
    gender: "female",
    size: "large",
    description: "Bella is a gorgeous Maine Coon with a luxurious coat. She's gentle, loving, and gets along well with everyone.",
    imageUrl: "https://images.pexels.com/photos/2071882/pexels-photo-2071882.jpeg",
    location: "Seattle, WA",
    status: "available",
  },
  {
    id: "5",
    name: "Charlie",
    type: "dog",
    breed: "Labrador Retriever",
    age: "5 years",
    gender: "male",
    size: "large",
    description: "Charlie is a well-trained Labrador with a calm demeanor. He's great with children and enjoys swimming and playing fetch.",
    imageUrl: "https://images.pexels.com/photos/1254140/pexels-photo-1254140.jpeg",
    location: "Los Angeles, CA",
    status: "available",
  },
  {
    id: "6",
    name: "Lily",
    type: "cat",
    breed: "Persian",
    age: "3 years",
    gender: "female",
    size: "medium",
    description: "Lily is a beautiful Persian cat with a long, fluffy coat. She's calm, enjoys being brushed, and likes to find cozy spots to nap.",
    imageUrl: "https://images.pexels.com/photos/96938/pexels-photo-96938.jpeg",
    location: "Denver, CO",
    status: "available",
  },
  // Additional pets
  {
    id: "7",
    name: "Rio",
    type: "bird",
    breed: "Macaw",
    age: "2 years",
    gender: "male",
    size: "medium",
    description: "Rio is a vibrant and talkative Macaw who loves to interact with people. He has an impressive vocabulary and loves to show off his colorful feathers.",
    imageUrl: "https://images.pexels.com/photos/1661179/pexels-photo-1661179.jpeg",
    location: "Miami, FL",
    status: "available",
  },
  {
    id: "8",
    name: "Nemo",
    type: "other",
    breed: "Clownfish",
    age: "1 year",
    gender: "male",
    size: "small",
    description: "Nemo is a playful clownfish who brings life to any aquarium. He's very active and gets along well with other fish.",
    imageUrl: "https://images.pexels.com/photos/128756/pexels-photo-128756.jpeg",
    location: "San Diego, CA",
    status: "available",
  },
  {
    id: "9",
    name: "Coco",
    type: "dog",
    breed: "French Bulldog",
    age: "2 years",
    gender: "female",
    size: "small",
    description: "Coco is a charming French Bulldog with a personality bigger than her size. She loves cuddles and playing with toys.",
    imageUrl: "https://images.pexels.com/photos/4587998/pexels-photo-4587998.jpeg",
    location: "Boston, MA",
    status: "available",
  },
  {
    id: "10",
    name: "Oliver",
    type: "cat",
    breed: "Siamese",
    age: "1 year",
    gender: "male",
    size: "medium",
    description: "Oliver is a curious and vocal Siamese cat who loves to follow his humans around and tell them about his day.",
    imageUrl: "https://images.pexels.com/photos/1770918/pexels-photo-1770918.jpeg",
    location: "Portland, OR",
    status: "available",
  },
  {
    id: "11",
    name: "Koko",
    type: "bird",
    breed: "African Grey Parrot",
    age: "3 years",
    gender: "female",
    size: "medium",
    description: "Koko is an intelligent African Grey Parrot who loves to learn new words and solve puzzles. She's incredibly smart and social.",
    imageUrl: "https://images.pexels.com/photos/56733/pexels-photo-56733.jpeg",
    location: "Austin, TX",
    status: "available",
  },
  {
    id: "12",
    name: "Rocky",
    type: "dog",
    breed: "Rottweiler",
    age: "4 years",
    gender: "male",
    size: "large",
    description: "Rocky is a gentle giant who's great with kids and other pets. He's well-trained and loves to play fetch.",
    imageUrl: "https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg",
    location: "Phoenix, AZ",
    status: "available",
  },
  {
    id: "13",
    name: "Milo",
    type: "cat",
    breed: "British Shorthair",
    age: "2 years",
    gender: "male",
    size: "medium",
    description: "Milo is a laid-back British Shorthair who loves to lounge around and watch the world go by. He's great with other cats.",
    imageUrl: "https://images.pexels.com/photos/2194261/pexels-photo-2194261.jpeg",
    location: "Chicago, IL",
    status: "available",
  },
  {
    id: "14",
    name: "Sunny",
    type: "bird",
    breed: "Cockatiel",
    age: "1 year",
    gender: "female",
    size: "small",
    description: "Sunny is a cheerful Cockatiel who loves to whistle tunes and sit on shoulders. She's very affectionate and social.",
    imageUrl: "https://images.pexels.com/photos/97533/pexels-photo-97533.jpeg",
    location: "Denver, CO",
    status: "available",
  },
  {
    id: "15",
    name: "Ziggy",
    type: "other",
    breed: "Bearded Dragon",
    age: "2 years",
    gender: "male",
    size: "small",
    description: "Ziggy is a calm and friendly bearded dragon who enjoys basking in the sun and eating his vegetables.",
    imageUrl: "https://images.pexels.com/photos/2062316/pexels-photo-2062316.jpeg",
    location: "Las Vegas, NV",
    status: "available",
  },
  {
    id: "16",
    name: "Daisy",
    type: "dog",
    breed: "Pomeranian",
    age: "1 year",
    gender: "female",
    size: "small",
    description: "Daisy is a fluffy ball of energy who loves to play and cuddle. She's great with families and other small dogs.",
    imageUrl: "https://images.pexels.com/photos/2607544/pexels-photo-2607544.jpeg",
    location: "Seattle, WA",
    status: "available",
  },
  {
    id: "17",
    name: "Shadow",
    type: "cat",
    breed: "Black Bombay",
    age: "3 years",
    gender: "male",
    size: "medium",
    description: "Shadow is a sleek black cat with a mysterious personality. He's independent but loving with his chosen people.",
    imageUrl: "https://images.pexels.com/photos/1741205/pexels-photo-1741205.jpeg",
    location: "San Francisco, CA",
    status: "available",
  },
  {
    id: "18",
    name: "Bubbles",
    type: "other",
    breed: "Goldfish",
    age: "1 year",
    gender: "female",
    size: "small",
    description: "Bubbles is a beautiful fancy goldfish with flowing fins. She's peaceful and adds a calming presence to any room.",
    imageUrl: "https://images.pexels.com/photos/1076122/pexels-photo-1076122.jpeg",
    location: "Miami, FL",
    status: "available",
  },
  {
    id: "19",
    name: "Zeus",
    type: "dog",
    breed: "Great Dane",
    age: "3 years",
    gender: "male",
    size: "large",
    description: "Zeus is a gentle giant who thinks he's a lap dog. He's well-trained and great with children despite his size.",
    imageUrl: "https://images.pexels.com/photos/1490908/pexels-photo-1490908.jpeg",
    location: "Houston, TX",
    status: "available",
  },
  {
    id: "20",
    name: "Pip",
    type: "bird",
    breed: "Budgie",
    age: "1 year",
    gender: "female",
    size: "small",
    description: "Pip is a colorful and active budgie who loves to chirp and play with toys. She's perfect for first-time bird owners.",
    imageUrl: "https://images.pexels.com/photos/2317904/pexels-photo-2317904.jpeg",
    location: "Orlando, FL",
    status: "available",
  }
]; 